### ISSUE TITLE
Please update versionCode in gradle

### ISSUE THREAD

**Issue by IzzySoft** [huckleberrypie/Pollywog#1]
When updating to v0.2 you seem to have forgotten the `versionCode` [in your gradle](https://github.com/huckleberrypie/Pollywog/blob/master/app/build.gradle):

```
        versionCode 1
        versionName "0.2"
```

As it still shows the same number you used in v0.1, F-Droid won't find the update. Could you please increase `versionCode` so your app can be build again? Thanks in advance!

**Comment by huckleberrypie** [comment]
So it should be 2 then, right?

**Comment by IzzySoft** [comment]
@huckleberrypie Yes. Important is just that it's a number and bigger than the previous one – so take a pattern suiting you. I've seen devs using "prefixes", like "10020" for v1.0.0.20, for example.

Thanks! I'm triggering the F-Droid update then.

**Comment by IzzySoft** [comment]
Well, update in F-Droid failed as the tag still points to the "old commit" with the wrong versionCode. Could you please retag?

**Comment by huckleberrypie** [comment]
There, hope the new release rollout would fix things.

**Comment by IzzySoft** [comment]
Hope so, too:

    Parsing manifest at 'build/org.strawberryforum.pollywog/app/build.gradle'
    ..got package=org.strawberryforum.pollywog, version=0.2, vercode=2

looks fine, but

    Parsing manifest at 'build/org.strawberryforum.pollywog/app/src/main/AndroidManifest.xml'
    ..got package=org.strawberryforum.pollywog, version=v0.2.1, vercode=1

is a bit confusing. I'm no dev, but from what I've seen so far I guess you should define the version only in one place – either in gradle or in manifest.

I've updated the metadata at F-Droid, let's see what happens. Hopefully the correct thing :wink:

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9234

**Comment by huckleberrypie** [comment]
> 
> 
> https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9234

Is it merged now?

**Comment by linsui** [comment]
Yes.
